# Generated by Django 4.2.7 on 2024-06-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='age',
            field=models.PositiveSmallIntegerField(default=17),
        ),
    ]
