# Generated by Django 4.2.7 on 2024-06-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0002_alter_utilisateur_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salles',
            name='classe',
            field=models.CharField(choices=[('TERMINAL D', 'Terminal D'), ('TERMINAL C', 'Terminal C'), ('TERMINAL A', 'TerminalA'), ('TERMINAL TI', 'Terminal TI'), ('PREMIERE D', 'Premiere D'), ('PREMIERE C', 'Premiere C'), ('PREMIERE TI', 'Premiere TI'), ('PREMIERE A', 'Premiere A'), ('SECONDE C', 'SecondeC'), ('SECONDE A', 'SecondeA'), ('TROSIEME', 'Troisieme'), ('QUATRIEME', 'Quatrieme'), ('CINQUIEME', 'Ciquieme'), ('SIXIEME', 'Sixieme'), ('COURS MOYENS DEUX', 'Cour Moyen Deux'), ('COURS MOYEN UN', 'Cour Moyen Un'), ('COURS ELEMENTAIRE DEUX', 'CourElementaire Deux')], max_length=30),
        ),
    ]
