# Generated by Django 4.2.7 on 2024-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0004_alter_salles_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Programme_objectif',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='niveau',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
