# Generated by Django 4.2.7 on 2024-06-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0005_alter_client_programme_objectif_alter_client_niveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='classe',
        ),
        migrations.AddField(
            model_name='matiere',
            name='classe',
            field=models.ManyToManyField(to='MbokoAPI.salles'),
        ),
    ]
