# Generated by Django 4.2.7 on 2024-06-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0006_remove_matiere_classe_matiere_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Difficulete',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Objectif',
        ),
        migrations.RemoveField(
            model_name='ensegnant',
            name='classe_tenue',
        ),
        migrations.RemoveField(
            model_name='ensegnant',
            name='specialise',
        ),
        migrations.AddField(
            model_name='client',
            name='Difficulete',
            field=models.ManyToManyField(null=True, to='MbokoAPI.matiere'),
        ),
        migrations.AddField(
            model_name='client',
            name='Objectif',
            field=models.ManyToManyField(null=True, to='MbokoAPI.objectif'),
        ),
        migrations.AddField(
            model_name='ensegnant',
            name='classe_tenue',
            field=models.ManyToManyField(null=True, to='MbokoAPI.salles'),
        ),
        migrations.AddField(
            model_name='ensegnant',
            name='specialise',
            field=models.ManyToManyField(null=True, to='MbokoAPI.matiere'),
        ),
    ]
