# Generated by Django 4.2.7 on 2024-06-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0007_remove_client_difficulete_remove_client_objectif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Difficulete',
            field=models.ManyToManyField(to='MbokoAPI.matiere'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Objectif',
            field=models.ManyToManyField(to='MbokoAPI.objectif'),
        ),
        migrations.AlterField(
            model_name='ensegnant',
            name='Taux_d_echec',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ensegnant',
            name='Taux_de_reussite',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ensegnant',
            name='classe_tenue',
            field=models.ManyToManyField(to='MbokoAPI.salles'),
        ),
        migrations.AlterField(
            model_name='ensegnant',
            name='nombre_de_requete',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ensegnant',
            name='specialise',
            field=models.ManyToManyField(to='MbokoAPI.matiere'),
        ),
    ]
