# Generated by Django 4.2.7 on 2024-06-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0008_alter_client_difficulete_alter_client_objectif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Objectif',
        ),
    ]
