# Generated by Django 4.2.7 on 2024-06-21 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0009_remove_client_objectif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensegnant',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
