# Generated by Django 4.2.7 on 2024-06-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0010_alter_ensegnant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensegnant',
            name='Moyen',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ensegnant',
            name='Taux_d_echec',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ensegnant',
            name='Taux_de_reussite',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ensegnant',
            name='nombre_de_requete',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
