# Generated by Django 4.2.7 on 2024-06-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0011_alter_ensegnant_moyen_alter_ensegnant_taux_d_echec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='photo',
            field=models.ImageField(default='exit', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Photo',
            field=models.ImageField(null=True, upload_to='Photo'),
        ),
    ]
