# Generated by Django 4.2.7 on 2024-06-28 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0016_remove_ensegnant_moyen_alter_note_nom_utilisateur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Nom_utilisateur',
            new_name='Nom_client',
        ),
        migrations.AddField(
            model_name='ensegnant',
            name='notations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MbokoAPI.note'),
        ),
        migrations.AlterField(
            model_name='ensegnant',
            name='nombre_de_requete',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('Nom_client', 'nom_repetiteur')},
        ),
    ]
