# Generated by Django 4.2.7 on 2024-06-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0017_rename_nom_utilisateur_note_nom_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='repetiteur',
            new_name='ensegnant',
        ),
        migrations.RenameField(
            model_name='requete',
            old_name='repiteur',
            new_name='ensegnant',
        ),
    ]
