# Generated by Django 4.2.7 on 2024-06-28 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0018_rename_repetiteur_commentaire_ensegnant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensegnant',
            name='notations',
        ),
        migrations.AlterField(
            model_name='note',
            name='Nom_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nom_client', to='MbokoAPI.client'),
        ),
        migrations.AlterField(
            model_name='note',
            name='nom_repetiteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nom_repetiteur', to='MbokoAPI.ensegnant'),
        ),
    ]
