# Generated by Django 4.2.7 on 2024-06-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0019_remove_ensegnant_notations_alter_note_nom_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='repetiteur',
            field=models.ManyToManyField(to='MbokoAPI.ensegnant'),
        ),
    ]
