# Generated by Django 4.2.7 on 2024-06-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0020_client_repetiteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectif',
            name='reussite',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
