# Generated by Django 4.2.7 on 2024-07-01 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0023_alter_note_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='note',
        ),
    ]
