# Generated by Django 4.2.7 on 2024-07-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0024_remove_livre_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='classe',
        ),
        migrations.AddField(
            model_name='livre',
            name='classe',
            field=models.ManyToManyField(to='MbokoAPI.salles'),
        ),
    ]
