# Generated by Django 4.2.7 on 2024-07-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0025_remove_livre_classe_livre_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='age',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='Date_de_naissance',
            field=models.DateField(null=True),
        ),
    ]
