# Generated by Django 4.2.7 on 2024-07-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0026_remove_utilisateur_age_utilisateur_date_de_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Difficulete',
            field=models.ManyToManyField(null=True, to='MbokoAPI.matiere'),
        ),
        migrations.AlterField(
            model_name='client',
            name='repetiteur',
            field=models.ManyToManyField(null=True, to='MbokoAPI.ensegnant'),
        ),
    ]
