# Generated by Django 4.2.7 on 2024-07-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0027_alter_client_difficulete_alter_client_repetiteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('Description', models.TextField()),
                ('localisation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reussite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_de_reussite', models.IntegerField()),
                ('annee', models.TextField()),
                ('id_etablissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MbokoAPI.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MbokoAPI.salles')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MbokoAPI.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='commentaire',
            name='id_etablissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MbokoAPI.etablissement'),
        ),
    ]
