# Generated by Django 4.2.7 on 2024-07-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0028_etablissement_reussite_citation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Response', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='livre',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reussite',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MbokoAPI.salles'),
        ),
        migrations.AddField(
            model_name='reussite',
            name='examen',
            field=models.TextField(null=True),
        ),
    ]
