# Generated by Django 4.2.7 on 2024-07-14 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0029_quizz_livre_description_reussite_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='Ville',
            field=models.TextField(choices=[('DOUALA', 'Douala'), ('YAOUNDE', 'Yaounde'), ('BERTOUA', 'Bertoua'), ('EBOLOWA', 'Ebolowa'), ('BUEA', 'Buea'), ('LIMBE', 'Limbe'), ('BAFOUSSAM', 'Bafoussam'), ('DSCHANG', 'Dschand'), ('KRIBI', 'Kribi'), ('MBANGA', 'Mbanga'), ('EDEA', 'Edea'), ('TIKO', 'Tiko'), ('MAROUA', 'Maroua'), ('GAROUA', 'Garoua'), ('NGAOUNDERE', 'Ngaoundere'), ('SOUZA', 'Souza')], default=django.utils.timezone.now, max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etablissement',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
