# Generated by Django 4.2.7 on 2024-07-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0030_etablissement_ville_etablissement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
