# Generated by Django 4.2.7 on 2024-07-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0031_etablissement_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ensegnant',
            old_name='classe_tenue',
            new_name='classe',
        ),
        migrations.AlterField(
            model_name='client',
            name='Difficulete',
            field=models.ManyToManyField(to='MbokoAPI.matiere'),
        ),
    ]
