# Generated by Django 4.2.7 on 2024-07-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0032_rename_classe_tenue_ensegnant_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='repetiteur',
            field=models.ManyToManyField(to='MbokoAPI.ensegnant'),
        ),
    ]
