# Generated by Django 4.2.7 on 2024-07-22 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0033_alter_client_repetiteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='niveau_du_livre',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
