# Generated by Django 4.2.7 on 2024-07-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0034_livre_niveau_du_livre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reussite',
            old_name='id_etablissement',
            new_name='etablissement',
        ),
    ]
