# Generated by Django 4.2.7 on 2024-07-27 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MbokoAPI', '0035_rename_id_etablissement_reussite_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerie',
            name='messager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Messagrie_messager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagerie',
            name='recepteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Messagerie_recepteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
